name: Feature Request
description: Suggest a feature to improve the extension
body:
- type: markdown
  attributes:
    value: |
      Please [search for existing issues](https://github.com/James-Yu/LaTeX-Workshop/issues) before creating a new one.

- type: textarea
  attributes:
    label: The Issue
    description: Is your feature request related to a problem? Please provide a clear and concise description of what the problem is.
  validations:
    required: true

- type: textarea
  attributes:
    label: The Solution
    description: Please provide a solution you would like to have.
  validations:
    required: true

- type: textarea
  attributes:
    label: Alternative Solutions
    description: Please provide a clear and concise description to any alternative solutions or features you considered.

- type: textarea
  attributes:
    label: Anything Else?
