name: Docker on Linux
on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: |
        npm ci
        npm run compile
        docker pull tianon/latex
    - name: Run tests
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: npm run test:docker
